
export type ClassLevel = '6' | '7' | '8' | '9' | '10' | '11' | '12' | 'COMPETITION';

export type Board = 'CBSE' | 'BSEB' | 'COMPETITION';

export type Stream = 'Science' | 'Commerce' | 'Arts';

export type Role = 'STUDENT' | 'ADMIN';

export type ContentType = 'NOTES_SIMPLE' | 'NOTES_PREMIUM' | 'MCQ_ANALYSIS' | 'MCQ_SIMPLE' | 'PDF_FREE' | 'PDF_PREMIUM' | 'PDF_ULTRA' | 'PDF_VIEWER' | 'WEEKLY_TEST' | 'VIDEO_LECTURE' | 'NOTES_HTML_FREE' | 'NOTES_HTML_PREMIUM';

export interface ExternalApp {
  id: string;
  name: string;
  url: string;
  icon?: string; // Optional icon name or url
  isLocked: boolean;
  creditCost: number;
}

export interface SubjectProgress {
  currentChapterIndex: number; // Starts at 0 (Chapter 1)
  totalMCQsSolved: number; // Must reach 100 to advance index
}

export interface InboxMessage {
  id: string;
  text: string;
  date: string;
  read: boolean;
  type?: 'TEXT' | 'REWARD';
  reward?: {
      tier: 'WEEKLY' | 'MONTHLY' | 'LIFETIME';
      level: 'BASIC' | 'ULTRA';
      durationHours: number;
  };
  expiresAt?: string;
  isClaimed?: boolean;
}

export interface User {
  id: string; // Login ID
  password: string;
  name: string;
  mobile: string;
  email: string;
  role: Role;
  createdAt: string;
  credits: number; // Premium Credits
  streak: number; // Consecutive days
  lastLoginDate: string; // ISO Date string YYYY-MM-DD
  lastActiveTime?: string; // ISO String for "Online" status
  redeemedCodes: string[]; // List of redeemed code IDs
  
  // Soft Delete / Ban Logic
  isArchived?: boolean; // Acts as Soft Delete / Recycle Bin
  isLocked?: boolean;   // NEW: Hard Lock (Login Denied, but not deleted)
  deletedAt?: string; // ISO Date when deleted. If > 30 days, auto purge.
  recoveryCode?: string; // Generated by Admin to restore account
  
  // GRANULAR BANS
  isChatBanned?: boolean; // Can't send messages
  isGameBanned?: boolean; // Can't play Spin Wheel
  
  // COMMUNICATION
  inbox?: InboxMessage[]; // Messages from Admin
  
  // REWARDS SYSTEM
  pendingRewards?: PendingReward[];
  isRewardsUnlocked?: boolean; // 10 Coin Gate

  // New Fields for Student Profile
  board?: Board;
  classLevel?: ClassLevel;
  stream?: Stream; // Only for 11/12
  
  // Chat & Premium Features
  isPremium?: boolean;
  lastChatTime?: string; // ISO String for cooldown
  lastSpinTime?: string; // ISO String (Legacy)
  dailySpinDate?: string; // YYYY-MM-DD for resetting daily count
  dailySpinCount?: number; // Number of spins used today
  lastRewardClaimDate?: string; // To track daily 3-hour study reward
  
  // SUBSCRIPTION MANAGEMENT
  subscriptionTier?: 'FREE' | 'WEEKLY' | 'MONTHLY' | 'YEARLY' | 'LIFETIME'; // Subscription level
  subscriptionLevel?: 'BASIC' | 'ULTRA'; // NEW: Granular level for Real subscribers
  subscriptionEndDate?: string; // ISO Date when subscription expires
  subscriptionPrice?: number; // Price admin set for this user's subscription
  grantedByAdmin?: boolean; // True if subscription was granted free by admin
  
  // Progress Tracking
  progress: Record<string, SubjectProgress>; // Key is subjectID
}

export interface CreditPackage {
  id: string;
  name: string;
  credits: number;
  price: number;
  color?: string; // Visual color for the card
}

export interface SubscriptionPlan {
  id: string;
  name: string;
  duration: string; // e.g., "7 days", "30 days"
  
  // Basic Tier (MCQ + Notes)
  basicPrice: number;
  basicOriginalPrice: number;
  
  // Advance/Ultra Tier (PDF + Video)
  ultraPrice: number;
  ultraOriginalPrice: number;
  
  features: string[]; // Generic features list or split logic
  popular?: boolean;
}

export interface RecycleBinItem {
  id: string; // Unique delete ID
  originalId: string; // ID of the actual item
  type: 'USER' | 'CHAPTER' | 'CONTENT' | 'POST';
  name: string; // For display
  data: any; // Full object to restore
  deletedAt: string;
  expiresAt: string; // 90 days later
  restoreKey?: string; // LocalStorage key to restore to
}

export interface PaymentRequest {
  id: string;
  userId: string;
  userName: string;
  packageId: string;
  packageName: string;
  amount: number;
  txnId: string; // User entered Transaction ID/UTR
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  timestamp: string;
}

// NEW INTERFACE
export interface RecoveryRequest {
  id: string; // User ID
  name: string;
  mobile: string;
  timestamp: string;
  status: 'PENDING' | 'RESOLVED';
}

export interface StartupConfig {
    enabled: boolean;
    duration: number; // Seconds
    title: string;
    features: string[]; // List of text
    bgColor: string;
    textColor: string;
}

export interface SystemSettings {
  appName: string;
  themeColor?: string; // NEW: Dynamic Hex Color
  maintenanceMode: boolean;
  maintenanceMessage?: string; // NEW: Custom text for maintenance screen
  customCSS: string; // For dynamic styling updates
  // NEW LOGIC CONTROLS
  apiKeys: string[];      // MULTIPLE API KEYS SUPPORT
  adminCode?: string;     // NEW: Dynamic Admin Password
  adminEmail?: string;    // NEW: Dynamic Admin Email
  adminPhones?: Array<{id: string, number: string, name: string, isDefault?: boolean}>; // MULTIPLE WhatsApp Numbers
  aiInstruction?: string; // NEW: Custom System Instruction for AI
  footerText?: string;    // NEW: Custom Footer Text
  
  // CONTENT CONTROL
  welcomeTitle?: string;  // NEW: Welcome Popup Title
  welcomeMessage?: string; // NEW: Welcome Popup Body
  termsText?: string;     // NEW: T&C Text
  supportEmail?: string;  // NEW: Support Email
  aiModel?: string;       // NEW: Select Gemeni Model (Flash vs Pro)

  // LIVE DASHBOARDS (Global Banners)
  marqueeLines: string[]; // ARRAY of 4-5 lines for scrolling text
  liveMessage1?: string;  // NEW: Top Live Dashboard
  liveMessage2?: string;  // NEW: Bottom Live Dashboard
  
  // EXTERNAL APPS
  externalApps?: ExternalApp[];

  // GAME CONFIG
  wheelRewards: number[]; // e.g., [0, 1, 2, 5, 10]

  chatCost: number;       // Default 1. If 0, it's free.
  dailyReward: number;    // Default 3
  signupBonus: number;    // Default 2
  isChatEnabled: boolean; // Global Toggle
  isGameEnabled?: boolean; // NEW: Global Game Toggle
  gameCost?: number;      // NEW: Cost per spin (credits)
  spinLimitUltra?: number; // NEW: Daily Limit for Ultra
  spinLimitBasic?: number; // NEW: Daily Limit for Basic
  spinLimitFree?: number;  // NEW: Daily Limit for Free/Normal
  defaultVideoCost?: number; // NEW: Global Default Video Price
  defaultPdfCost?: number;   // NEW: Global Default PDF Price
  allowSignup: boolean;   // New: Stop new registrations
  loginMessage: string;   // New: Custom message on Login Screen
  
  // VISIBILITY CONTROLS
  allowedClasses?: ClassLevel[]; // List of active classes
  allowedBoards?: Board[]; // List of active boards
  allowedStreams?: Stream[]; // List of active streams
  hiddenSubjects?: string[]; // List of Subject IDs to hide
  
  storageCapacity?: string; // NEW: Storage Limit Setting
  
  // MONETIZATION
  isPaymentEnabled?: boolean; // NEW: Master switch for payment
  paymentDisabledMessage?: string; // NEW: Message when locked
  upiId: string;          // Admin UPI ID
  upiName: string;        // Admin Name for Payment
  qrCodeUrl: string;      // Optional QR Image URL
  paymentInstructions: string; // "Pay and send screenshot..."
  packages: CreditPackage[]; // List of credit packages
  subscriptionPlans?: SubscriptionPlan[]; // List of subscription plans
  
  // WEEKLY TEST CONFIG
  weeklyTests?: WeeklyTest[]; // List of active weekly tests
  
  // POPUP AD CONFIG
  startupAd?: StartupConfig; 
}

export interface GiftCode {
  id: string;
  code: string;
  amount: number;
  createdAt: string;
  isRedeemed: boolean;
  redeemedBy?: string; // User ID
  redeemedDate?: string;
  generatedBy: string; // Admin ID (or name)
}

export interface PendingReward {
  id: string;
  type: 'COINS' | 'SUBSCRIPTION';
  amount?: number; // For Coins
  subTier?: 'WEEKLY' | 'MONTHLY' | 'LIFETIME'; // For Sub
  subLevel?: 'BASIC' | 'ULTRA';
  durationHours?: number;
  expiresAt: string;
  label: string;
}

export interface ChatMessage {
  id: string;
  userId: string;
  userName: string;
  userRole: Role;
  text: string;
  timestamp: string;
  isDeleted?: boolean; // Soft delete flag
  deletedAt?: string;  // For 30 day recovery
}

export interface IICPost {
  id: string;
  type: 'TEXT' | 'IMAGE' | 'VIDEO';
  title?: string;
  content: string; // Text content, Base64 Image string, or Video URL
  timestamp: string;
  authorName: string;
}

export interface Subject {
  id: string;
  name: string;
  icon: string;
  color: string;
}

export interface Chapter {
  id: string;
  title: string;
  description?: string;
}

export interface MCQItem {
  question: string;
  options: string[];
  correctAnswer: number; // Index 0-3
  explanation: string;
  mnemonic?: string; // Memory Trick
  concept?: string; // Full concept explanation
}

export interface LeaderboardEntry {
    id: string;
    userId: string;
    userName: string;
    score: number;
    total: number;
    date: string;
    topic: string;
}

export interface ActivityLogEntry {
  id: string;
  userId: string;
  userName: string;
  action: string; // 'LOGIN', 'SIGNUP', 'TEST', 'CONTENT', 'ADMIN'
  details: string;
  timestamp: string;
  role: Role;
}

export interface LessonContent {
  id: string; // unique ID for history
  title: string;
  subtitle: string;
  content: string; // URL for PDF/Link Mode
  type: ContentType;
  dateCreated: string;
  subjectName: string;
  mcqData?: MCQItem[]; // Structure for MCQ mode
  videoPlaylist?: {title: string, url: string, price?: number}[]; // NEW: Video Playlist
  videoPrice?: number; // Global or default video price
  ultraPdfLink?: string; // Ultra PDF
  ultraPdfPrice?: number; // Ultra PDF Price
  isComingSoon?: boolean; // If content is missing
}

export type ViewState = 'BOARDS' | 'CLASSES' | 'STREAMS' | 'SUBJECTS' | 'CHAPTERS' | 'LESSON' | 'ADMIN_DASHBOARD' | 'AUDIO_STUDIO' | 'STUDENT_DASHBOARD' | 'UNIVERSAL_CHAT' | 'RULES' | 'IIC' | 'LEADERBOARD';

export interface WeeklyTest {
  id: string;
  name: string;
  description: string;
  isActive: boolean;
  classLevel: ClassLevel;
  questions: MCQItem[];
  totalQuestions: number;
  passingScore: number;
  createdAt: string;
  durationMinutes?: number; // Default 120 (2 hours)
  autoSubmitEnabled?: boolean; // Auto-submit after timeout
  selectedSubjects?: string[]; // Subject IDs included in this test
  selectedChapters?: string[]; // Chapter IDs included in this test (mix from multiple)
}

export interface StudentTestAttempt {
  testId: string;
  userId: string;
  startedAt: string; // ISO timestamp
  submittedAt?: string;
  score?: number;
  answers: Record<number, number>; // question index -> selected answer index
}

export type StudentTab = 'ROUTINE' | 'CHAT' | 'HISTORY' | 'REDEEM' | 'PREMIUM' | 'GAME' | 'WEEKLY_TEST' | 'PROFILE' | 'LEADERBOARD' | 'STORE' | 'VIDEO' | 'PDF' | 'MCQ';

export type Language = 'English' | 'Hindi';

export interface AppState {
  user: User | null;
  originalAdmin: User | null; // NEW: Track Admin when viewing as user
  view: ViewState;
  selectedBoard: Board | null;
  selectedClass: ClassLevel | null;
  selectedStream: Stream | null;
  selectedSubject: Subject | null;
  selectedChapter: Chapter | null;
  chapters: Chapter[];
  lessonContent: LessonContent | null;
  loading: boolean;
  error: string | null;
  language: Language;
  showWelcome: boolean; // Control welcome popup
  globalMessage: string | null; // Admin Broadcast
  settings: SystemSettings; // New Global Settings
}
